# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Customized prompt
export PS1='\e[1;31m[ \e[1;33m\u\e[1;31m || \e[1;33m\h\e[1;31m || \e[1;32m\w\e[1;31m ]\n$ '
trap '[[ -t 1 ]] && tput sgr0' DEBUG
